In [ ]:
#connect my drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#go to the workplace
%cd drive/MyDrive/Colab\ Notebooks
%ls

/content/drive/MyDrive/Colab Notebooks
DATA/         dataf.xlsx  payoff_test.py  working_p1/  working_results/
Data01.ipynb  datat.xlsx  tutorial/       working_p2/


In [ ]:
%ls

DATA/         dataf.xlsx  payoff_test.py  working_p1/  working_results/
Data01.ipynb  datat.xlsx  tutorial/       working_p2/


In [ ]:
import numpy as np
import pandas as pd
import imp
import payoff_test as pt
from tqdm import tqdm

In [71]:
imp.reload(pt)

<module 'payoff_test' from '/content/drive/My Drive/Colab Notebooks/payoff_test.py'>

In [ ]:
data_user_facebook = np.array([
[0.21688537, 0.43129487, 0.35181976],
[0.45159693, 0.25030948, 0.29809359],
[0.10547165, 0.41619213, 0.47833622],
[0.0017331,  0.00321862, 0.99504828],
[0.00222827, 0.01163654, 0.98613518],
[0.00198069, 0.0034662,  0.99455311],
[2.22827433e-03, 9.90344145e-04, 9.96781382e-01],
[0.00321862, 0.00247586, 0.99430552],
[1.48551622e-03, 9.90344145e-04, 9.97524140e-01],
[0.98885863, 0.00965586, 0.00148552],
[0.99579104, 0.00297103, 0.00123793],
[0.99603862, 0.00272345, 0.00123793],
[0.31691013, 0.23099777, 0.4520921],
[0.29759842, 0.30774944, 0.39465214],
[0.24659569, 0.31195841, 0.4414459 ],
[0.00470413, 0.00272345, 0.99257242],
[0.00148552, 0.00123793, 0.99727655],
[0.00148552, 0.00470413, 0.99381035],
[9.94553107e-01, 4.70413469e-03, 7.42758108e-04],
[9.96286209e-01, 2.72344640e-03, 9.90344145e-04],
[0.99579104, 0.00272345, 0.00148552],
[9.97524140e-01, 2.22827433e-03, 2.47586036e-04],
[0.98341174, 0.0089131,  0.00767517],
[0.98019312, 0.01807378, 0.0017331 ],
[0.27977222, 0.32235702, 0.39787076],
[0.10769993, 0.37682595, 0.51547413],
[0.16687299, 0.17108195, 0.66204506]])

In [ ]:
data_company = np.array([[2.82864201, 2.74971243, 2.80345982, 2.73353287, 2.78371589],
[3.28544902, 3.22364505, 3.28792612, 3.25118884, 3.1421941],
[2.12300113, 2.08944107, 2.10620577, 2.17510654, 2.12474159],
[-2.61370805, -2.71557954, -2.6871004 , -2.67831302, -2.69103087],
[-2.13062108, -2.14840642, -2.1307547 , -2.11130918, -2.1005282],
[-2.44592455, -2.46945351, -2.46510049, -2.52190763, -2.52458476],
[-2.80903993, -2.76062529, -2.75088828, -2.73559514, -2.81720466],
[-2.18638094, -2.1690045 , -2.16737619, -2.19780711, -2.13953166],
[-2.90895531, -2.98168008, -3.06467904, -3.03741288, -3.03674708],
[4.31361184, 4.25716409, 4.19093735, 4.31762513, 4.22690498],
[4.01427743, 4.21017867, 3.84297728, 3.85129114, 3.81301227],
[3.9823014 , 3.9072578 , 3.88750464, 3.84076434, 3.9825669],
[4.17211912, 4.06090897, 4.17258634, 4.11003157, 4.31202906],
[4.13294074, 4.277631  , 4.18161521, 4.01862496, 4.25029431],
[3.93810911, 3.9467988 , 4.00140573, 3.90926558, 3.84494737],
[-1.36930236, -1.39187512, -1.40198776, -1.36756901, -1.37179185],
[-2.71548776, -2.69503082, -2.75925976, -2.77060633, -2.71312176],
[-2.45673025, -2.37294731, -2.32144155, -2.39868591, -2.35216345],
[4.83296297, 4.79377853, 4.99366911, 4.672734  , 4.90065215],
[4.53540195, 4.60668054, 4.7001681 , 4.6703857 , 4.80252011],
[4.66465303, 4.70111069, 4.81020229, 4.39082626, 4.68171744],
[4.55488826, 4.57727549, 4.63529448, 4.49436085, 4.50192577],
[5.0238507 , 5.12352284, 4.94826687, 4.94134901, 4.98415358],
[5.26322085, 5.06117136, 5.44494389, 5.20602698, 5.27261982],
[4.84534005, 4.76940514, 5.02656617, 4.83851617, 4.86919476],
[4.01966264, 3.93014149, 3.9245841 , 3.99303158, 3.98554033],
[4.21338837, 4.04840545, 4.11827048, 4.0894646 , 4.07046431]])

In [ ]:
writer = pd.ExcelWriter('dataf.xlsx')

In [ ]:
dtr = pd.DataFrame(data_user)
dtr.to_excel(writer,'user',float_format='%.2f')
writer.save()

In [ ]:
dtr = pd.DataFrame(data_company)
dtr.to_excel(writer,'company',float_format='%.2f')
writer.save()

In [ ]:
writer.close()

In [ ]:
data_user_twitter = np.array([
[0.29345928, 0.41725088, 0.28928984],
[0.07192581, 0.45370575, 0.47436844],
[0.60936462, 0.01827663, 0.37235874],
[0.04923376, 0.35061373, 0.60015251],
[0.00252134, 0.18227437, 0.81520429],
[0.00371436, 0.20613485, 0.79015079],
[0.00274273, 0.06150838, 0.9357489 ],
[0.00255824, 0.05240696, 0.94503481],
[0.00223846, 0.14289228, 0.85486926],
[0.00241065, 0.00455071, 0.99303864],
[0.97680368, 0.0031117,  0.02008462],
[0.98131749, 0.00357907, 0.01510344],
[0.87040317, 0.01453767, 0.11505916],
[0.2429095,  0.22522323, 0.53186727],
[0.63194598, 0.02261826, 0.34543576],
[0.01526333, 0.34207808, 0.6426586 ],
[0.00275502, 0.24693135, 0.75031363],
[0.00767471, 0.28728507, 0.70504022],
[0.03061275, 0.11048385, 0.8589034 ],
[0.99455145, 0.0031855,  0.00226306],
[0.99451455, 0.00343148, 0.00205397],
[0.97556146, 0.00564534, 0.0187932 ],
[0.87560574, 0.01031904, 0.11407522],
[0.98060414, 0.00525176, 0.0141441 ],
[0.73791602, 0.10635131, 0.15573266],
[0.24576292, 0.22474356, 0.52949352],
[0.52950582, 0.12577178, 0.34472241],
[0.09266229, 0.34560795, 0.56172976]
])

In [ ]:
data_company = np.array([
[5.14996985, 5.11414103, 5.30937009, 5.20973356, 5.40604251],
[6.18301553, 6.37827508, 6.1988278 , 6.21781408, 6.13103198],
[4.75437262, 4.99109523, 4.548371  , 4.87142958, 4.8418545 ],
[2.12589917, 2.15913778, 2.04900518, 2.09981443, 2.08373261],
[2.49224036, 2.54969845, 2.51203326, 2.36392737, 2.63528981],
[1.92963057, 1.94352342, 1.93312886, 1.96333985, 1.83904963],
[1.7304093 , 1.71413581, 1.76925798, 1.811965  , 1.76181491],
[1.92874504, 1.87552734, 1.83697361, 1.9589719 , 2.01488171],
[1.15324018, 1.1776189 , 1.16324236, 1.11509985, 1.15040235],
[7.76342969, 7.5832284 , 7.81483933, 7.86291692, 7.61680095],
[7.96408303, 7.84207629, 7.88954653, 7.69381419, 7.81569939],
[8.15699299, 8.15719637, 7.91648629, 8.03575897, 8.24441118],
[7.5199591 , 8.00419274, 7.72112788, 7.61009537, 7.87982776],
[8.06120226, 7.92714281, 7.71231056, 7.87045693, 8.12084505],
[5.190382  , 5.07389008, 5.11187619, 5.09766018, 5.02021657],
[3.36029233, 3.35473972, 3.45171994, 3.43853824, 3.50201381],
[4.20527554, 4.53352475, 4.6030297 , 4.51853664, 4.37433421],
[5.40765745, 5.57632824, 5.46150655, 5.30345344, 5.58605311],
[9.0168189 , 9.04554619, 8.97913915, 8.90908099, 8.75097538],
[8.97044574, 8.63089561, 9.12531281, 9.26588216, 8.78275279],
[9.19091476, 8.93157206, 9.35919761, 9.06063861, 9.12763726],
[9.20394861, 9.11320549, 9.16279593, 8.8561664 , 9.00234915],
[9.10796474, 8.94016593, 8.99186914, 9.25922246, 8.97881635],
[ 9.81173531,  9.47224904, 10.03697958,  9.6805341 , 10.04695593],
[8.93650075, 8.81418706, 8.86980351, 9.06940859, 8.844812  ],
[9.11194507, 9.56151523, 9.54361403, 9.42418402, 9.5619767 ],
[7.82539694, 7.95883362, 8.02675492, 7.93449079, 8.00309966]
])

In [ ]:
writer = pd.ExcelWriter('datat.xlsx')

In [ ]:
dtr = pd.DataFrame(data_user)
dtr.to_excel(writer,'user',float_format='%.2f')
writer.save()

In [ ]:
dtr = pd.DataFrame(data_company)
dtr.to_excel(writer,'company',float_format='%.2f')
writer.save()

In [ ]:
writer.close()

In [ ]:
data_parameter_facebook=[
{'a':3,'b':3,'cn':5,'n':4039},
{'a':3,'b':3,'cn':5,'n':4039},
{'a':3,'b':3,'cn':5,'n':4039},
{'a':3,'b':5,'cn':5,'n':4039},
{'a':3,'b':5,'cn':5,'n':4039},
{'a':3,'b':5,'cn':5,'n':4039},
{'a':3,'b':7,'cn':5,'n':4039},
{'a':3,'b':7,'cn':5,'n':4039},
{'a':3,'b':7,'cn':5,'n':4039},
{'a':5,'b':3,'cn':5,'n':4039},
{'a':5,'b':3,'cn':5,'n':4039},
{'a':5,'b':3,'cn':5,'n':4039},
{'a':5,'b':5,'cn':5,'n':4039},
{'a':5,'b':5,'cn':5,'n':4039},
{'a':5,'b':5,'cn':5,'n':4039},
{'a':5,'b':7,'cn':5,'n':4039},
{'a':5,'b':7,'cn':5,'n':4039},
{'a':5,'b':7,'cn':5,'n':4039},
{'a':7,'b':3,'cn':5,'n':4039},
{'a':7,'b':3,'cn':5,'n':4039},
{'a':7,'b':3,'cn':5,'n':4039},
{'a':7,'b':5,'cn':5,'n':4039},
{'a':7,'b':5,'cn':5,'n':4039},
{'a':7,'b':5,'cn':5,'n':4039}, 
{'a':7,'b':7,'cn':5,'n':4039},
{'a':7,'b':7,'cn':5,'n':4039},
{'a':7,'b':7,'cn':5,'n':4039},              
]

In [ ]:
data_parameter_twitter=[
{'a':3,'b':3,'cn':5,'n':81306},
{'a':3,'b':3,'cn':5,'n':81306},
{'a':3,'b':3,'cn':5,'n':81306},
{'a':3,'b':5,'cn':5,'n':81306},
{'a':3,'b':5,'cn':5,'n':81306},
{'a':3,'b':5,'cn':5,'n':81306},
{'a':3,'b':7,'cn':5,'n':81306},
{'a':3,'b':7,'cn':5,'n':81306},
{'a':3,'b':7,'cn':5,'n':81306},
{'a':5,'b':3,'cn':5,'n':81306},
{'a':5,'b':3,'cn':5,'n':81306},
{'a':5,'b':3,'cn':5,'n':81306},
{'a':5,'b':5,'cn':5,'n':81306},
{'a':5,'b':5,'cn':5,'n':81306},
{'a':5,'b':5,'cn':5,'n':81306},
{'a':5,'b':7,'cn':5,'n':81306},
{'a':5,'b':7,'cn':5,'n':81306},
{'a':5,'b':7,'cn':5,'n':81306},
{'a':7,'b':3,'cn':5,'n':81306},
{'a':7,'b':3,'cn':5,'n':81306},
{'a':7,'b':3,'cn':5,'n':81306},
{'a':7,'b':5,'cn':5,'n':81306},
{'a':7,'b':5,'cn':5,'n':81306},
{'a':7,'b':5,'cn':5,'n':81306}, 
{'a':7,'b':7,'cn':5,'n':81306},
{'a':7,'b':7,'cn':5,'n':81306},
{'a':7,'b':7,'cn':5,'n':81306},              
]

In [72]:
platform_facebook = []
company_facebook = []
for i in tqdm (range(27), desc="Loading..."):
  gt = pt.GameTest(data_parameter_facebook[i], data_user_facebook[i])  # 4039, 81306
  payoffs = gt.random_payoff_result()
  platform_facebook.append(payoffs['rnd_platform'])
  company_facebook.append(payoffs['rnd_company'])
print(np.array(platform_facebook))
print(np.array(company_facebook))

Loading...: 100%|██████████| 27/27 [00:04<00:00,  5.61it/s]

[25.2434128  25.57572452 24.21948411  7.5711906   8.82810637  7.55893412
 -0.75938829  0.81437679 -1.19581348 12.6116288  11.45832925 11.42148868
 10.60900976 11.04141279 10.94938567 -6.08418727 -8.39642269 -7.01276466
  4.32378932  4.1083344   4.47110144 -4.63308015 -0.62367815 -1.41434491
 -3.53072642 -4.30505185 -4.34256594]
[[-1.4513425  -1.40257606 -1.44419653 -1.45257685 -1.48924306]
 [-1.2227106  -1.20641004 -1.16477547 -1.24047196 -1.19698707]
 [-1.68740276 -1.66068688 -1.73381279 -1.6977972  -1.71772202]
 [-3.9630098  -4.0075114  -4.00736362 -3.95946706 -3.97292415]
 [-3.69008847 -3.73821312 -3.63344395 -3.60364822 -3.69275407]
 [-3.79643697 -3.81508724 -3.91342326 -3.84789198 -3.9588694 ]
 [-3.98202697 -3.9265734  -3.94671259 -4.00570917 -3.87569878]
 [-3.73183163 -3.70646617 -3.6878269  -3.6912768  -3.84712424]
 [-4.13500013 -4.13577359 -4.16779339 -4.11516046 -4.12317442]
 [-0.08523355 -0.0564713  -0.07586324 -0.0687873  -0.07696467]
 [-0.25248053 -0.27793072 -0.30488982 -0

In [73]:
platform_twitter = []
company_twitter = []
for i in tqdm (range(27), desc="Loading..."):
  gt = pt.GameTest(data_parameter_twitter[i], data_user_twitter[i])  # 4039, 81306
  payoffs = gt.random_payoff_result()
  platform_twitter.append(payoffs['rnd_platform'])
  company_twitter.append(payoffs['rnd_company'])
print(np.array(platform_twitter))
print(np.array(company_twitter))

Loading...: 100%|██████████| 27/27 [00:03<00:00,  7.48it/s]

[ 26.89493314  25.11834319  25.19288038  14.61627027  10.0283481
  10.7677296   -0.53082425  -0.4929225    0.05111758   6.8179318
  12.2785963   12.34901387   5.18427381   6.50172712   5.62075082
  -6.6428705   -9.10975795  -7.67282458   3.54193454   0.9507923
   1.10851471  -6.74647595  -4.96655574  -7.22382346 -12.83771558
 -12.77208218 -12.5456776 ]
[[ 2.24741951e-01  1.76339339e-01  2.13815426e-01  2.41620276e-01
   2.09918706e-01]
 [-3.08738891e-01 -2.95624391e-01 -3.06859098e-01 -2.40800529e-01
  -2.96103557e-01]
 [ 1.22426081e-01  1.35220836e-01  1.19891041e-01  1.25067104e-01
   1.54440644e-01]
 [-4.63682984e-01 -4.62133942e-01 -4.20009244e-01 -4.43166035e-01
  -4.88588235e-01]
 [-1.75875560e+00 -1.72304081e+00 -1.70908761e+00 -1.70284212e+00
  -1.66720771e+00]
 [-1.60464056e+00 -1.55860205e+00 -1.56145419e+00 -1.55700503e+00
  -1.53749389e+00]
 [-1.83484417e+00 -1.81538596e+00 -1.81657929e+00 -1.83391536e+00
  -1.79433147e+00]
 [-1.93385482e+00 -1.92141744e+00 -1.90046803e+00 

In [77]:
writer_f = pd.ExcelWriter('dataf1.xlsx')
writer_t = pd.ExcelWriter('datat1.xlsx')

In [78]:
dtr = pd.DataFrame(platform_facebook)
dtr.to_excel(writer_f,'platform',float_format='%.4f')
writer_f.save()
dtr = pd.DataFrame(company_facebook)
dtr.to_excel(writer_f,'company',float_format='%.4f')
writer_f.save()
writer_f.close()

In [79]:
dtr = pd.DataFrame(platform_twitter)
dtr.to_excel(writer_t,'platform',float_format='%.4f')
writer_t.save()
dtr = pd.DataFrame(company_twitter)
dtr.to_excel(writer_t,'company',float_format='%.4f')
writer_t.save()
writer_t.close()